spring:
  application:
    name: chirp

  data:
    redis:
      host: ${REDIS_URL}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
      port: ${REDIS_PORT}
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000                     #ms
      idle-timeout: 300000                          #ms
      max-lifetime: 12000000                        #ms
      validation-timeout: 5000                      #ms
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30                           #s
        connectTimeout: 10                          #s
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USERNAME}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: true
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          max-attempts: 3
          multiplier: 2
  mail:
    port: ${SMPT_PORT}
    host: ${SMPT_HOST}
    username: ${SMPT_USERNAME}
    password: ${SMPT_PASSWORD}
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enabled: true
  thymeleaf:
    suffix: .html


jwt:
  secret: ${JWT_SECRET}

chirp:
  email:
    url: ${EMAIL_URL}
    from: ${EMAIL_FROM}
    verification:
      expiry-hours: 24
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)