spring:
  application:
    name: chirp

  data:
    redis:
      host: ${REDIS_URL}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
      port: ${REDIS_PORT}
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000                     #ms
      idle-timeout: 300000                          #ms
      max-lifetime: 12000000                        #ms
      validation-timeout: 5000                      #ms
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30                           #s
        connectTimeout: 10                          #s
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

jwt:
  secret: ${JWT_SECRET}

chirp:
  email:
    verification:
      expiry-hours: 24
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)